#!/bin/bash
echo "***************************************************************************"
echo "****************Bienvenue sur le script de mise a jour !*******************"
echo "***************************************************************************"
#on mets tous les packets a jour avec ce qui suit
sudo apt update
sudo apt upgrade

Upgradabl='apt list --upgradable'

function Upgradable {
for file in $($Upgradabl | awk -F'/' '{print $1}')
  do 
sudo apt install $file --upgrade
done
}

for file in $(sudo apt upgrade)
  do 
   if [[ $file = "apt list --upgradable" ]]
    then 
      Upgradable Upgradabl
   fi
 done

sudo apt dist-upgrade
sudo apt autoremove --purge
sudo apt autoclean
sudo apt clean
flatpak update
sudo snap refresh
#permet de retirer les anciennes dépendances devenue inutile de snap
LANG=C snap list --all | awk '/disabled/{print $1, $3}' | while read snapname revision ; do sudo snap remove "$snapname" --revision="$revision" ; done
echo "*****Fin du script de mise a jour !*******"  
echo "******************************************"  
